const CASES={rookie:[['ORBIT','Science','A path traced around another body.'],['JAGUAR','Wildlife','A spotted hunter of the Americas.'],['NEBULA','Space','A luminous cloud between stars.'],['CIPHER','Cryptography','A secret method of writing.'],['VOLCANO','Nature','A mountain with fire beneath it.'],['PHANTOM','Mystery','Something sensed but never held.']],operative:[['BLACKOUT','Urban','When an entire city loses its light.'],['PARADOX','Logic','A truth that contradicts itself.'],['SOVEREIGN','Power','One who answers to no higher authority.'],['LABYRINTH','Mythology','A place designed to make escape difficult.'],['RENDEZVOUS','Espionage','A meeting arranged in secrecy.'],['SPECTRUM','Physics','The full range hidden inside light.'],['QUARANTINE','Protocol','Isolation imposed to prevent spread.'],['AFTERMATH','Conflict','What remains when the event is over.']],nightmare:[['OBFUSCATE','Deception','To deliberately make meaning unclear.'],['SYZYGY','Astronomy','Three celestial bodies in alignment.'],['MNEMONIC','Cognition','A pattern that helps memory.'],['VICARIOUS','Psychology','Experienced through another person.'],['ZEITGEIST','Culture','The defining spirit of an era.'],['EQUINOX','Astronomy','When day and night reach balance.'],['CACOPHONY','Sound','A violent collision of noise.']]};
const ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('');
const CLUES={
ORBIT:['It describes a repeating journey through space.','Gravity keeps an object on this curved path.','Moons and satellites follow one around a planet.'],JAGUAR:['This subject is powerful and stealthy.','It is a large cat native to the Americas.','Its spotted coat hides it in rainforest shadows.'],NEBULA:['This object exists far beyond Earth.','It is made from enormous clouds of gas and dust.','Stars are often born inside it.'],CIPHER:['It protects meaning from unwanted readers.','Letters or symbols are systematically transformed.','Codebreakers try to solve it.'],VOLCANO:['Pressure builds beneath this natural formation.','It can release ash, gas, and molten rock.','It is a mountain connected to magma below.'],PHANTOM:['It seems present despite having no solid form.','Stories describe it as an apparition.','Another common word for a ghost.'],
BLACKOUT:['Normal activity stops when something essential disappears.','It can affect one building or an entire city.','During one, every electric light goes dark.'],PARADOX:['It challenges ordinary reasoning.','Its parts appear logically incompatible.','A statement that contradicts itself yet may be true.'],SOVEREIGN:['This word is associated with supreme authority.','It may describe a monarch or an independent state.','It answers to no higher governing power.'],LABYRINTH:['Its design makes navigation intentionally difficult.','Ancient myth placed a Minotaur inside one.','A vast and complicated maze.'],RENDEZVOUS:['People arrive at an agreed place and time.','Agents may arrange one in secrecy.','A prearranged meeting.'],SPECTRUM:['It contains a continuous range rather than one point.','A prism makes its visible form easy to see.','The band of colors hidden inside white light.'],QUARANTINE:['This protocol separates a possible danger.','It limits the spread of disease.','A temporary period of enforced isolation.'],AFTERMATH:['It cannot exist until a major event has ended.','It describes consequences following conflict or disaster.','The state of things left behind afterward.'],
OBFUSCATE:['This action makes understanding more difficult.','It is often done deliberately to hide the truth.','To make a message obscure or unclear.'],SYZYGY:['This rare term is used in astronomy.','It involves a straight-line celestial arrangement.','The alignment of three astronomical bodies.'],MNEMONIC:['It is a tool rather than the memory itself.','Rhymes and acronyms can serve as one.','A pattern designed to help you remember.'],VICARIOUS:['The experience belongs directly to somebody else.','You might feel it while watching another succeed.','Experienced indirectly through another person.'],ZEITGEIST:['This German loanword describes a collective atmosphere.','Art and ideas can capture it.','The defining spirit of a particular era.'],EQUINOX:['It occurs twice during Earth’s orbit.','The Sun crosses the celestial equator.','Day and night become approximately equal.'],CACOPHONY:['It is heard, not seen.','Many harsh sounds collide without harmony.','A loud and unpleasant mixture of noises.']};
const settings={rookie:{attempts:10,mult:.8},operative:{attempts:8,mult:1},nightmare:{attempts:6,mult:1.5}};
const ORIGINS={ORBIT:'Latin orbita — “track” or “wheel rut.”',JAGUAR:'Tupi–Guarani yaguara, through Portuguese.',NEBULA:'Latin nebula — “mist” or “cloud.”',CIPHER:'Arabic ṣifr — “zero” or “empty.”',VOLCANO:'Italian vulcano, named for Vulcan, Roman god of fire.',PHANTOM:'Greek phantasma — “image” or “apparition.”',BLACKOUT:'An English compound: black + out.',PARADOX:'Greek paradoxon — “contrary to expectation.”',SOVEREIGN:'Old French soverain — “supreme.”',LABYRINTH:'Greek labyrinthos, the legendary maze of Crete.',RENDEZVOUS:'French rendez-vous — “present yourselves.”',SPECTRUM:'Latin spectrum — “appearance” or “image.”',QUARANTINE:'Italian quaranta giorni — “forty days.”',AFTERMATH:'Old English: the second mowing after harvest.',OBFUSCATE:'Latin obfuscare — “to darken.”',SYZYGY:'Greek syzygia — “yoked together.”',MNEMONIC:'Greek mnēmōn — “remembering.”',VICARIOUS:'Latin vicarius — “substitute.”',ZEITGEIST:'German Zeit (time) + Geist (spirit).',EQUINOX:'Latin aequus (equal) + nox (night).',CACOPHONY:'Greek kakos (bad) + phōnē (sound).'};
const EXAMPLES={ORBIT:'The satellite entered a stable orbit around Mars.',JAGUAR:'A jaguar moved silently along the riverbank.',NEBULA:'The telescope revealed newborn stars inside the nebula.',CIPHER:'The message was protected by a complex cipher.',VOLCANO:'Scientists monitored the volcano for pressure changes.',PHANTOM:'A phantom shape appeared through the fog.',BLACKOUT:'The blackout left every street in darkness.',PARADOX:'Saving time by rushing created a strange paradox.',SOVEREIGN:'The nation became sovereign after independence.',LABYRINTH:'The old city felt like a labyrinth of narrow streets.',RENDEZVOUS:'The teams reached the rendezvous before dawn.',SPECTRUM:'Visible light is part of the electromagnetic spectrum.',QUARANTINE:'The plant entered quarantine to protect nearby crops.',AFTERMATH:'Communities rebuilt in the aftermath of the storm.',OBFUSCATE:'Jargon can obfuscate an otherwise simple idea.',SYZYGY:'The eclipse occurred during a syzygy of Sun, Moon, and Earth.',MNEMONIC:'ROYGBIV is a mnemonic for rainbow colors.',VICARIOUS:'She felt vicarious pride in her student’s success.',ZEITGEIST:'The film captured the hopeful zeitgeist of the decade.',EQUINOX:'At the equinox, daylight and darkness nearly balance.',CACOPHONY:'A cacophony of alarms echoed through the station.'};
let mode='operative',current=null,guessed=new Set(),mistakes=0,active=false,hintUsed=false,soundOn=true,clueLevel=0,demoTimers=[],demoActive=false;
let stats=JSON.parse(localStorage.getItem('nightfall_stats')||'{"played":0,"won":0,"streak":0,"best":0,"solved":0,"score":500}');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const wordEl=$('#word'),keyboard=$('#keyboard'),figure=$('#figureWrap'),toast=$('#toast');

function boot(){ALPHABET.forEach(l=>{const b=document.createElement('button');b.className='key';b.textContent=l;b.dataset.letter=l;b.onclick=()=>guess(l);keyboard.appendChild(b)});bind();new MutationObserver(()=>{if($('#resultDialog').open)showLearning()}).observe($('#resultDialog'),{attributes:true,attributeFilter:['open']});updateStats();clock();setInterval(clock,1000);weather();renderAttempts();}
function bind(){
  $('#modeSelect').onclick=e=>{const b=e.target.closest('button');if(!b)return;mode=b.dataset.mode;$$('#modeSelect button').forEach(x=>x.classList.toggle('active',x===b));tone(420,.05)};
  $('#launchBtn').onclick=()=>{demoActive=false;$('#startScreen').classList.add('hidden');newCase()};$('#demoBtn').onclick=startDemo;$('#newGameBtn').onclick=()=>{demoActive=false;newCase()};$('#continueBtn').onclick=()=>{demoActive=false;$('#resultDialog').close();newCase()};$('#dialogClose').onclick=()=>$('#resultDialog').close();
  $('#hintBtn').onclick=hint;$('#clueBtn').onclick=nextClue;$('#skipDemo').onclick=()=>stopDemo();$('#soundBtn').onclick=()=>{soundOn=!soundOn;$('#soundBtn').textContent=soundOn?'◖))':'◖×';tone(520,.06)};
  $('#statsBtn').onclick=showStats;$('#statsClose').onclick=()=>$('#statsDialog').close();$('#homeBtn').onclick=()=>$('#startScreen').classList.remove('hidden');
  addEventListener('keydown',e=>{if(/^[a-z]$/i.test(e.key))guess(e.key.toUpperCase());if(e.key==='Escape')$$('dialog[open]').forEach(d=>d.close())});
}
function newCase(forced=null){stopDemo(false);const pool=CASES[mode],previous=current?.[0];if(forced)current=forced;else do{current=pool[Math.floor(Math.random()*pool.length)]}while(pool.length>1&&current[0]===previous);guessed.clear();mistakes=0;hintUsed=false;clueLevel=1;active=true;figure.dataset.stage='0';figure.style.opacity='.08';$('#caseNo').textContent='CASE #'+String(Math.floor(1000+Math.random()*9000));$('#difficultyLabel').textContent=mode.toUpperCase();$('#category').textContent=current[1].toUpperCase();$('#subjectStatus').textContent='PROTOCOL ACTIVE';$$('.key').forEach(k=>{k.disabled=false;k.className='key'});renderWord();renderClues();renderAttempts();tone(170,.12,'sawtooth')}
function renderWord(reveal=false){wordEl.innerHTML='';[...current[0]].forEach(ch=>{const s=document.createElement('span');s.className='letter';if(ch===' '){s.classList.add('space')}else if(guessed.has(ch)||reveal){s.textContent=ch;s.classList.add('revealed')}wordEl.appendChild(s)})}
function renderAttempts(){const max=settings[mode].attempts;$('#attemptRail').innerHTML=Array.from({length:max},(_,i)=>`<i class="${i<mistakes?'lost':''}"></i>`).join('')}
function renderClues(){const list=CLUES[current[0]]||[current[2]];$('#clues').innerHTML=list.slice(0,clueLevel).map((c,i)=>`<p class="${i===clueLevel-1?'new':''}">${c}</p>`).join('');$('#clueCount').textContent=`${clueLevel} / ${list.length} CLUES`;$('#clueBtn').disabled=clueLevel>=list.length}
function nextClue(){if(!active)return;const list=CLUES[current[0]]||[current[2]];if(clueLevel>=list.length){notify('ALL INTELLIGENCE ALREADY VISIBLE');return}if(!demoActive&&stats.score<30){notify('INSUFFICIENT CREDITS');return}if(!demoActive)stats.score-=30;clueLevel++;renderClues();save();updateStats();tone(520,.1);notify('NEW CASE INTELLIGENCE ADDED')}
function guess(l){if(!active||guessed.has(l)||!current)return;guessed.add(l);const key=$(`.key[data-letter="${l}"]`);key.disabled=true;if(current[0].includes(l)){key.classList.add('correct');tone(640,.08);renderWord();if([...current[0]].every(c=>c===' '||guessed.has(c)))finish(true)}else{key.classList.add('wrong');mistakes++;renderAttempts();figure.dataset.stage=String(Math.min(6,Math.ceil(mistakes/settings[mode].attempts*6)));figure.style.opacity=String(.16+mistakes*.08);$('#subjectStatus').textContent=`THREAT LEVEL ${String(mistakes).padStart(2,'0')}`;wordEl.classList.remove('shake');void wordEl.offsetWidth;wordEl.classList.add('shake');tone(90,.25,'sawtooth');if(mistakes===Math.ceil(settings[mode].attempts*.65)&&Math.random()>.35){document.body.classList.add('flash');setTimeout(()=>document.body.classList.remove('flash'),600)}if(mistakes>=settings[mode].attempts)finish(false)}}
function hint(){if(!active)return;if(hintUsed){notify('LETTER ASSIST ALREADY CONSUMED');return}if(stats.score<120){notify('INSUFFICIENT CREDITS');return}const unknown=[...new Set([...current[0]].filter(c=>c!==' '&&!guessed.has(c)))];if(!unknown.length)return;stats.score-=120;hintUsed=true;const l=unknown[Math.floor(Math.random()*unknown.length)];guessed.add(l);const key=$(`.key[data-letter="${l}"]`);key.disabled=true;key.classList.add('correct');renderWord();save();updateStats();tone(800,.15,'sine');notify(`LETTER ${l} EXPOSED`)}
function finish(win){active=false;stats.played++;let earned=0;if(win){earned=Math.round((260-mistakes*22)*settings[mode].mult);stats.won++;stats.solved++;stats.streak++;stats.best=Math.max(stats.best,stats.streak);stats.score+=earned;$('#resultKicker').textContent='CASE RESOLVED';$('#resultTitle').innerHTML='SIGNAL<br>RECOVERED';$('#resultText').textContent=`“${current[0]}” was recovered with ${settings[mode].attempts-mistakes} attempts remaining.`;tone(420,.12);setTimeout(()=>tone(630,.16),130)}else{stats.streak=0;$('#resultKicker').textContent='PROTOCOL FAILED';$('#resultTitle').innerHTML='SIGNAL<br>LOST';$('#resultText').textContent=`The word was “${current[0]}”. The city keeps its secret tonight.`;renderWord(true);tone(65,.55,'sawtooth')}$('#earned').textContent=(earned?'+':'')+String(earned).padStart(3,'0');$('#subjectStatus').textContent=win?'SUBJECT SECURED':'CONNECTION TERMINATED';$$('.key').forEach(k=>k.disabled=true);save();updateStats();setTimeout(()=>$('#resultDialog').showModal(),700)}
function updateStats(){$('#streak').textContent=String(stats.streak).padStart(2,'0');$('#solved').textContent=String(stats.solved).padStart(2,'0');$('#score').textContent=String(stats.score).padStart(4,'0')}
function showLearning(){if(!current)return;const word=current[0],clues=CLUES[word]||[current[2]];$('#learnWord').textContent=word;$('#learnDefinition').textContent=clues[clues.length-1];$('#learnOrigin').textContent=ORIGINS[word]||'Origin information is being researched.';$('#learnExample').textContent=EXAMPLES[word]||`The operative added “${word.toLowerCase()}” to the case report.`;$('#learnMemory').textContent=`REMEMBER · ${clues[0]}`}
function save(){localStorage.setItem('nightfall_stats',JSON.stringify(stats))}function showStats(){$('#statPlayed').textContent=stats.played;$('#statWin').textContent=(stats.played?Math.round(stats.won/stats.played*100):0)+'%';$('#statBest').textContent=stats.best;$('#statCredits').textContent=stats.score;$('#statsDialog').showModal()}
function notify(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove('show'),1800)}
function clock(){const d=new Date();$('#clock').textContent=[d.getHours(),d.getMinutes(),d.getSeconds()].map(n=>String(n).padStart(2,'0')).join(':')}
function startDemo(){mode='rookie';$$('#modeSelect button').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));$('#startScreen').classList.add('hidden');newCase(CASES.rookie[0]);const coach=$('#demoCoach'),text=$('#demoText');coach.classList.add('show');const step=(ms,msg,fn)=>demoTimers.push(setTimeout(()=>{text.textContent=msg;if(fn)fn()},ms));step(100,'Every case begins with a category, a hidden word, and one descriptive clue.');step(2600,'Choose letters using your keyboard or the on-screen controls. Correct letters illuminate the signal.',()=>guess('O'));step(5200,'A wrong guess advances the threat meter—but clues help you reason before guessing.',()=>guess('X'));step(7800,'NEXT CLUE adds clearer intelligence. REVEAL LETTER is a stronger, more expensive assist.',()=>nextClue());step(10400,'Demo complete. Finish this practice case yourself—your controls are now active.',()=>setTimeout(()=>coach.classList.remove('show'),3500))}
function stopDemo(hide=true){demoTimers.forEach(clearTimeout);demoTimers=[];if(hide)$('#demoCoach').classList.remove('show')}
function tone(freq,duration,type='sine'){if(!soundOn)return;try{const C=window.AudioContext||window.webkitAudioContext,c=new C(),o=c.createOscillator(),g=c.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(.035,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+duration);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+duration);o.onended=()=>c.close()}catch(e){}}
function weather(){const c=$('#weather'),x=c.getContext('2d');let drops=[];function size(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);drops=Array.from({length:Math.min(180,innerWidth/5)},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,l:8+Math.random()*20,s:8+Math.random()*12,a:.05+Math.random()*.13}))}function draw(){x.clearRect(0,0,innerWidth,innerHeight);x.lineWidth=.7;for(const d of drops){x.strokeStyle=`rgba(170,220,225,${d.a})`;x.beginPath();x.moveTo(d.x,d.y);x.lineTo(d.x-2,d.y+d.l);x.stroke();d.y+=d.s;if(d.y>innerHeight){d.y=-d.l;d.x=Math.random()*innerWidth}}requestAnimationFrame(draw)}addEventListener('resize',size);size();draw()}
boot();
